server:
  port : 2103

spring:
  application :
    name : spring-security-client

  datasource :
    url : jdbc:mysql://localhost:3306/spring_security
    username : root
    password : root
    driver-class-name : com.mysql.cj.jdbc.Driver

  jpa :
    show-sql : true
    hibernate :
      ddl-auto : update